apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  selector:
    app: traefik
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 80
      nodePort: 31080
    - name: websecure
      port: 443
      targetPort: 443
      nodePort: 31443
    - name: admin
      port: 8080
      targetPort: 8080
      nodePort: 31808
